from enum import Enum
class PeEditions(Enum):
    """Enum para las ediciones del formato Primera Era."""
    EL_RETO = "el_reto"
    MUNDO_GOTICO = "mundo_gotico"
    IRA_DEL_NAHUAL = "ira_del_nahual"
    RAGNAROK = "ragnarok"
    COFRADIA = "cofradia"
    ESPIRITU_DEL_DRAGON = "espiritu_del_dragon"
    LEYENDAS_PRIMERA_ERA = "leyendas_primera_era"
    PROMOCIONALES_PRIMERA_ERA = "promocionales_primera_era"
    RACIALES_PE = "raciales_pe"
    EXTENSION_PE = "eXtension_pe"
    LEYENDAS_PRIMERA_ERA_2022 = "leyendas_primera_era_2022"
    TOOLKIT_WALKIRIAS = "toolkit_walkirias"
    TOOLKIT_ODIN = "toolkit_odin"
    LEYENDAS_PRIMERA_ERA_2023 = "leyendas_primera_era_2023"
    MUNDO_MEDIEVAL_EL_RETO = "mundo_medieval_el_reto"
    XINNIAN = "xinnian"
    TOOLKIT_PUERTAS_DEL_VALHALLA = "toolkit_puertas_del_valhalla"
    TOOLKIT_JUSTA = "toolkit_justa"
    MUNDOS_PERDIDOS_HORRORES_DE_SALEM = "mundos_perdidos_horrores_de_salem"
    MUNDOS_PERDIDOS_CIUDAD_DE_LOS_CESARES = "mundos_perdidos_ciudad_de_los_cesares"
    MUNDOS_PERDIDOS_LA_SAGA_DE_VOLSUNG = "mundos_perdidos_la_saga_de_volsung"
    MUNDOS_PERDIDOS_LEYENDAS_DE_AVALON = "mundos_perdidos_leyendas_de_avalon"
    MUNDOS_PERDIDOS_VIAJES_AL_OESTE = "mundos_perdidos_viaje_al_oeste"
    MUNDOS_PERDIDOS_SEÑORES_DEL_TRUENO = "mundos_perdidos_senores_del_trueno"
    VIGILANTES_DE_LA_NOCHE = "vigilantes_de_la_noche"
    LOOTBOX_PE_2024 = "lootbox_pe_2024"
    TOOLKIT_HONOR_Y_FEROCIDAD = "toolkit_honor_y_ferocidad"
    TOOLKIT_VALENTIA_Y_DESOLACION = "toolkit_valentia_y_desolacion"
    XINNIAN_AÑO_SERPIENTE_2025 = "xinnian_año_serpiente_2025"


class PbEditions(Enum):
    """Enum para las ediciones del formato Primer Bloque."""
    ESPADA_SAGRADA = "espada_sagrada"
    CRUZADAS = "cruzadas"
    HELENICA = "helenica"
    IMPERIO = "imperio"
    HIJOS_DE_DAANA = "hijos_de_daana"
    TIERRAS_ALTAS = "tierras_altas"
    DOMINIOS_DE_RA = "dominios_de_ra"
    ENCRUCIJADA = "encrucijada"
    LEYENDAS_PRIMER_BLOQUE = "leyendas_primer_bloque"
    PROMOCIONALES_PRIMER_BLOQUE = "promocionales_primer_bloque"
    RACIALES_PB = "raciales_pb"
    SHOGUN_I = "shogun_1"
    LEYENDAS_PRIMER_BLOQUE_2 = "primer_bloque_2"
    TOOLKIT_DRAGON_DORADO = "toolkit_dragon_dorado"
    TOOLKIT_FE_SIN_LIMITE = "toolkit_fe_sin_limite"
    EXTENSIONES_PRIMER_BLOQUE_2023 = "extensiones_pb_2023"
    ESPADA_SAGRADA_ANIVERSARIO = "espada_sagrada_aniversario"
    RELATOS_ESPADA_SAGRADA_ANIVERSARIO = "relatos_espada_sagrada_aniversario"
    COLECCIONES_RACIALES_PB_2023 = "colecciones_raciales_pb_2023"
    HELENICA_ANIVERSARIO = "helenica_aniversario"
    SHOGUN_II = "shogun_ii"
    DRACULA = "dracula_pb"
    LOOTBOX_2023 = "pb_lootbox_2023"
    LEYENDAS_PRIMER_BLOQUE_3 = "leyendas_pb_3.0" #here
    TOOLKIT_FUERZA_Y_DESTINO = "toolkit_pb_fuerza_y_destino"
    TOOLKIT_MAGIA_Y_DIVINIDAD = "toolkit_pb_magia_y_divinidad"
    RELATOS_DE_HELENICA_MAR_DE_POSEIDON = "relatos_hel_mar_de_poseidon"
    RELATOS_DE_HELENICA_CAMINOS_DE_TESEO = "relatos_hel_camino_de_teseo"
    RELATOS_DE_HELENICA_LABERINTO_DEL_MINOTAURO = "relatos_hel_laberinto_del_minotauro"
    HIJOS_DE_DAANA_ANIVERSARIO = "daana_aniversario"
    SHOGUN_III = "shogun_iii"
    INFERNO_EL_CAMINO_DE_DANTE = "dante_pb"

class SbEditions(Enum):
    """Enum para las ediciones del formato Segundo Bloque."""
    GUERRERO_JAGUAR = "guerrero_jaguar"
    VENDAVAL = "vendaval"
    BARBARIE = "barbarie"
    REINO_DE_ACERO = "reino_de_acero"
    HORDAS = "hordas"
    BESTIARIO = "bestiario"
    HEROES = "heroes"
    LEYENDAS_SEGUNDO_BLOQUE = "leyendas_segundo_bloque"
    PROMOCIONALES_SEGUNDO_BLOQUE = "promocionales_segundo_bloque"


class FxEditions(Enum):
    """Enum para las ediciones del formato Furia Extendido."""
    FURIA = "furia" 
    LEYENDAS_BLOQUE_FURIA = "leyendas_bloque_furia" 
    ROMA = "roma" 
    EXCALIBUR = "excalibur" 
    TROYA = "troya" 
    GUERREROS_DEL_SOL = "guerreros_del_sol" 
    GUARDIANES_DE_DAANA = "guardianes_de_daana" 
    FURIA_EXTENSION = "furiaext" 
    EXCALIBUR_EXTENSION = "extension_excalibur" 
    TROYA_EXTENSION = "extension_troya" 
    LEYENDAS_DE_METAL = "leyendas_de_metal" 
    MAZOS_FX = "mazos_fx" 
    COFRADIA = "la_cofradia" 
    KINGDOM_QUEST = "kingdom_quest" 
    VIGILANTES = "vigilantes" 
    FURIA_ANIVERSARIO = "producto_especial_furia_aniversario" 


class NeEditions(Enum):
    """Enum para las ediciones de Nueva Era (y formato Imperio)."""
    SUMERIA = "sumeria"
    REBELION = "rebelion"
    ASGARD = "asgard"
    MIDGARD = "midgard"
    CAMELOT = "camelot"
    TEMPLARIOS = "templarios"
    BUSHIDO = "bushido"
    SOL_NACIENTE = "sol-naciente"
    DOMINIO = "dominio"
    CONTRAATAQUE = "contraataque"
    AGUILA_IMPERIAL = "aguila-imperial"
    STEAMPUNK = "steampunk"
    AXIS_MUNDI = "axis-mundi"
    HIJOS_DEL_SOL = "hijos-del-sol"
    LEGADO_GOTICO = "legado-gotico"
    KEMET = "kemet"
    DHARMA = "dharma"
    OLIMPIA = "olimpia"
    CALAVERA = "calavera"
    KILIMANJARO = "kilimanjaro"
    ARSENAL = "arsenal"
    TINTA_INMORTAL = "tinta-inmortal"
    TERRORES_NOCTURNOS = "terrores-nocturnos"
    INVASION_OSCURA = "invasion-oscura"
    DINASTIA_DEL_DRAGON = "dinastia-del-dragon"
    HERMANOS_GRIMM = "hermanos-grimm"
    KELTOI = "keltoi"
    CUENTOS_DE_ULTRATUMBA = "cuentos-de-ultratumba"
    TIERRA_AUSTRAL = "tierra-austral"
    CONJUROS = "conjuros"
    ANGELES_Y_DEMONIOS = "angeles-demonios"
    AJEDREZ = "ajedrez"
    ESCUELAS_ELEMENTALES = "escuelas-elementales"
    ACERO = "acero"
    TINTA_INMORTAL_ROBIN_HOOD = "tinta_inmortal_robin_hood"
    TINTA_INMORTAL_ROMEO_Y_JULIETA = "tinta_inmortal_romeo_y_julieta"
    HERMANOS_GRIMM_EL_SASTRECILLO_VALIENTE_Y_LOS_MUSICOS_DE_BREMEN = "hermanos_grimm_elsastrecillovaliente_y_musicosdebremen"
    HERMANOS_GRIMM_EL_AGUA_DE_LA_VIDA_Y_JOHN_DE_ACERO = "hermanos_grimm_elaguadelavida_y_johndeacero"
    CUENTOS_DE_TERROR_EDGAR_ALLA_POE = "cuentos_de_terror_poe"
    CUENTOS_DE_TERROR_HP_LOVECRAFT = "cuentos_de_terror_lovecraft"
    CID = "cid"
    COLECCION_RACIAL_2022 = "coleccion_racial_2022"
    MASTER_TOOLKIT_2022 = "master_toolkit_2022"
    DESPERTAR_GOTICO = "despertar_gotico"
    EXPLORANDUM = "explorandum"
    MASTERTOOLKIT_2023 = "mastertoolkit_2023"
    GUARDIANES_DEL_REINO_I = "guardianes_reino_uno"
    GUARDIANES_DEL_REINO_II = "guardianes_reino_dos"
    VALHALLA = "valhalla"
    NEO_MIDDGARD = "neo_midgard"
    RELATOS_DEL_DESPERTAR_GOTICO = "relatos_del_despertar_gotico"
    EXTENSION_VALHALLA = "extension_valhalla"
    LA_VENGANZA_DE_HORUS = "la_venganza_de_horus"
    VISIONES_DE_KEMET = "visiones_de_kemet"
    CHILE_OSCURO = "chile_oscuro"
    NAPOLEON = "napoleon"
    RACIALES_2024 = "raciales_imp_2024"
    GIGER = "giger"
    ESPIRITU_SAMURAI = "espiritu_samurai"
    ZODIACO = "zodiaco"
    AMENAZA_KAIJU = "amenazakaiju"
    ESCUADRON_MECHA = "escuadronmecha"
    BESTIARIUM = "bestiarium"
    SECRETOS_ARCANOS = "secretos_arcanos"
    LOOTBOX_2024 = "lootbox_2024"
    HIELO_INMORTAL = "toolkit_hielo_inmortal"
    CENIZAS_DE_FUEGO = "toolkit_cenizas_de_fuego"