from enum import Enum
class PeEditions(Enum):
    """Enum para las ediciones del formato Primera Era."""
    EL_RETO = "el_reto"


class PbEditions(Enum):
    """Enum para las ediciones del formato Primer Bloque."""
    ESPADA_SAGRADA = "espada_sagrada"
    CRUZADAS = "cruzadas"
    HELENICA = "helenica"
    IMPERIO = "imperio"
    HIJOS_DE_DAANA = "hijos_de_daana"
    TIERRAS_ALTAS = "tierras_altas"
    DOMINIOS_DE_RA = "dominios_de_ra"
    ENCRUCIJADA = "encrucijada"
    LEYENDAS_PRIMER_BLOQUE = "leyendas_primer_bloque"
    PROMOCIONALES_PRIMER_BLOQUE = "promocionales_primer_bloque"
    RACIALES_PB = "raciales_pb"
    SHOGUN_I = "shogun_1"
    LEYENDAS_PRIMER_BLOQUE_2 = "primer_bloque_2"
    TOOLKIT_DRAGON_DORADO = "toolkit_dragon_dorado"
    TOOLKIT_FE_SIN_LIMITE = "toolkit_fe_sin_limite"
    EXTENSIONES_PRIMER_BLOQUE_2023 = "extensiones_pb_2023"
    ESPADA_SAGRADA_ANIVERSARIO = "espada_sagrada_aniversario"
    #RELATOS_ESPADA_SAGRADA_ANIVERSARIO = "relatos_espada_sagrada_aniversario"
    #COLECCIONES_RACIALES_PB_2023 = "colecciones_raciales_pb_2023"
    HELENICA_ANIVERSARIO = "helenica_aniversario"
    SHOGUN_II = "shogun_ii"
    DRACULA = "dracula_pb"
    #LOOTBOX_2023 = "pb_lootbox_2023"
    LEYENDAS_PRIMER_BLOQUE_3 = "leyendas_pb_3.0"
    TOOLKIT_FUERZA_Y_DESTINO = "toolkit_pb_fuerza_y_destino"
    TOOLKIT_MAGIA_Y_DIVINIDAD = "toolkit_pb_magia_y_divinidad"
    #RELATOS_DE_HELENICA_MAR_DE_POSEIDON = "relatos_hel_mar_de_poseidon"
    #RELATOS_DE_HELENICA_CAMINOS_DE_TESEO = "relatos_hel_camino_de_teseo"
    #RELATOS_DE_HELENICA_LABERINTO_DEL_MINOTAURO = "relatos_hel_laberinto_del_minotauro"
    HIJOS_DE_DAANA_ANIVERSARIO = "daana_aniversario"
    SHOGUN_III = "shogun_iii"
    INFERNO_EL_CAMINO_DE_DANTE = "dante_pb"

class SbEditions(Enum):
    """Enum para las ediciones del formato Segundo Bloque."""
    GUERRERO_JAGUAR = "guerrero_jaguar"
    VENDAVAL = "vendaval"
    BARBARIE = "barbarie"
    REINO_DE_ACERO = "reino_de_acero"
    HORDAS = "hordas"
    BESTIARIO = "bestiario"
    HEROES = "heroes"
    LEYENDAS_SEGUNDO_BLOQUE = "leyendas_segundo_bloque"
    PROMOCIONALES_SEGUNDO_BLOQUE = "promocionales_segundo_bloque"


class FxEditions(Enum):
    """Enum para las ediciones del formato Furia Extendido."""
    FURIA = "furia" 
    LEYENDAS_BLOQUE_FURIA = "leyendas_bloque_furia" 
    ROMA = "roma" 
    EXCALIBUR = "excalibur" 
    TROYA = "troya" 
    GUERREROS_DEL_SOL = "guerreros_del_sol" 
    GUARDIANES_DE_DAANA = "guardianes_de_daana" 
    FURIA_EXTENDIDO = "furiaext" 
    EXCALIBUR_EXTENSION = "extension_excalibur" 
    TROYA_EXTENSION = "extension_troya" 
    LEYENDAS_DE_METAL = "leyendas_de_metal" 
    MAZOS_FX = "mazos_fx" 
    COFRADIA = "la_cofradia" 
    KINGDOM_QUEST = "kingdom_quest" 
    VIGILANTES = "vigilantes" 
    FURIA_ANIVERSARIO = "producto_especial_furia_aniversario" 


class NeEditions(Enum):
    """Enum para las ediciones de Nueva Era (y formato Imperio)."""
    SUMERIA = "sumeria"